### ISSUE TITLE
Append Unreal ContentBrowser Folder Context Menu?

### ISSUE THREAD

**Issue by Ruka1998** [hannesdelbeke/unimenu#59]
![FolderContextAppend](https://github.com/hannesdelbeke/unimenu/assets/48833884/697b6238-42c1-4d94-b46e-91a9d483afc3)

`# -*- coding: utf-8 -*-
parent_path: ContentBrowser.FolderContextMenu

label: FolderContextMenu # also tried ContentBrowser.FolderContextMenu
items:
- label: TA Tool
  separator: True
  
- label: SyncToAssetByPath
  command: from utility.sync_to_asset_by_path import SyncToAssetByPath;SyncToAssetByPath()
  
- label: CheckAssets
  command: from utility.asset_check import CheckAssets;CheckAssets()
`

**Comment by Ruka1998** [comment]
Hey, I find a way listed as follows, but not sure is this a proper solution to this problem.
``` python
_abstract.py
......
elif self.items:  # submenu
+   if self.label == self._get_parent_app_node_name(parent_app_node=parent_app_node):
+      for item in self.items:
+          item.setup(parent_app_node=parent_app_node)
+   else:
       self.app_node = self._setup_sub_menu(parent_app_node=parent_app_node)
           for item in self.items:
                item.setup(parent_app_node=self.app_node)
......
+@abstractmethod
+def _get_parent_app_node_name(self, parent_app_node=None):
+    """get the default parent name for the root node, optional method"""
+    pass


unreal.py
+def _get_parent_app_node_name(self, parent_app_node: unreal.ToolMenu = None):
+    return parent_app_node.menu_name if parent_app_node else ""
```

**Comment by hannesdelbeke** [comment]
Hi, thank you for taking the time to post this issue.
I don't understand what is going on exactly, could you explain a bit more in detail what is going on, and what the issue is?

**Comment by Ruka1998** [comment]
Sorry for not explaining clearly. What I hope to achieve is to directly place a MenuEntry under the root directory ContentBrowserFolderContext by configuring YAML, rather than as a SubMenuEntry.

Specifically, let's say I have a MenuEntry called AssetCheck. Its location should be ContentBrowserFolderContext->AssetCheck instead of ContentBrowserFolderContext-><AnyLabel>->AssetCheck.

So in the previous response, I modified the setup() method in abstract.py to ensure that in the implementation of unreal.py, it checks whether each label in items matches a specific unreal.ToolMenu's menu_name. If they match, the parent of that item is set to a specific unreal.ToolMenu.

**Comment by hannesdelbeke** [comment]
ah i see, so you want to add several menu items to an existing menu.
instead of a submenu.

i think this needs some more thought, since I can't think on what the YAML would look like for now.

should be something like this probably
```YAML
existing parent
- child menuitem
- child menuitem
```

i wonder if something like this would work
```yaml
- label: TA Tool
  separator: True
  parent_path: ContentBrowser.FolderContextMenu
  
- label: SyncToAssetByPath
  command: from utility.sync_to_asset_by_path import SyncToAssetByPath;SyncToAssetByPath()
  parent_path: ContentBrowser.FolderContextMenu
  
- label: CheckAssets
  command: from utility.asset_check import CheckAssets;CheckAssets()
  parent_path: ContentBrowser.FolderContextMenu
```
